---
jobs:
  build:
    docker:
      -
        environment:
          MAVEN_OPTS: "-Xmx3200m"
        image: "circleci/openjdk:11-jdk"
      -
        environment:
          POSTGRES_DB: writerslife-sqldb
          POSTGRES_PASSWORD: postgres
          POSTGRES_USER: postgres
        image: "circleci/postgres:9.6.2-alpine"
    steps:
      - checkout
      -
        restore_cache:
          keys:
            - "v1-dependencies-{{ checksum \"pom.xml\" }}"
            - v1-dependencies-
      -
        run: "mvn dependency:go-offline"
      -
        save_cache:
          key: "v1-dependencies-{{ checksum \"pom.xml\" }}"
          paths:
            - ~/.m2
      -
        run: "mvn integration-test"
    working_directory: ~/repo
version: 2
